### ISSUE TITLE
Port hashes do not depend on patches

### ISSUE THREAD

**Issue by nfeske** [skalk/genode-imx#2]
In https://github.com/skalk/genode-imx8mq/blob/main/ports/mnt_reform2_linux.port#L17 a shell command is used to apply patches collected using a shell command. This has the unfortunate effect that a change of a patch does not affect the port hash as it should. E.g., I just ran into trouble updating to the usb branch, which ultimately needed a clean prepare_port.

This problem can be solved best by listing the patches in the PATCHES variable, which is the official way of handling patches. The variable may be populated using a `$(wildcard)`.

Alternatively, the port file could extend the HASH_INPUT variable.

**Comment by skalk** [comment]
Well, adding the patches to the PATCHES variable is not easily possible. The patches reside within the sources, which have to be downloaded. Therefore, it's not possible to hash them explicitely. I wonder why this is an issue at all, because the are implicitely hashed by the remote sources, aren't they?

So I do not understand why a change to the usb branch lead to an undetected port change for you.

**Comment by nfeske** [comment]
I completely missed that the patches are shipped with the archives. So you're right that they should be covered by the port hash.

> So I do not understand why a change to the usb branch lead to an undetected port change for you.

I don't understand this either but merely noticed that a hard remove of the `contrib/mnt_reform2_linux-<hash>` directory followed by a fresh prepare_port solved my build problem.

I have no tangible suggestion of how to investigate this further (due to me wiping the evidence). So I'm closing this issue, potentially re-opening it once the problem occurs again.
